# Generated by superclaude cli-portify
"""CLI Portify — programmatic CLI pipeline runner.

Ports inference-based SuperClaude workflows (commands + skills + agents)
into deterministic Python-controlled pipelines.
"""
