"""Utility helpers for the CLI Portify pipeline."""

from __future__ import annotations

import hashlib
import re
from pathlib import Path
from typing import Any


def parse_frontmatter(content: str) -> tuple[dict[str, Any], str]:
    """Parse YAML-style frontmatter from a Markdown string.

    Returns:
        (frontmatter_dict, body_string) — frontmatter dict is empty if
        the content does not start with '---'.
    """
    if not content.startswith("---"):
        return {}, content

    # Find the closing ---
    rest = content[3:]
    end_idx = rest.find("\n---")
    if end_idx == -1:
        return {}, content

    fm_text = rest[:end_idx].strip()
    body = rest[end_idx + 4 :].lstrip("\n")

    fm: dict[str, Any] = {}
    for line in fm_text.splitlines():
        if ":" not in line:
            continue
        key, _, val = line.partition(":")
        key = key.strip()
        val = val.strip()
        # Type coercion: int, float, bool, string
        if val.lower() == "true":
            fm[key] = True
        elif val.lower() == "false":
            fm[key] = False
        else:
            try:
                fm[key] = int(val)
            except ValueError:
                try:
                    fm[key] = float(val)
                except ValueError:
                    fm[key] = val

    return fm, body


def hash_section(content: str) -> str:
    """Return a stable SHA-256 hex digest for section content.

    Leading/trailing whitespace is stripped before hashing.
    """
    normalized = content.strip()
    return hashlib.sha256(normalized.encode("utf-8")).hexdigest()


def extract_sections(content: str) -> dict[str, str]:
    """Extract ## headings and their body text from Markdown content.

    Returns a dict of {section_title: body_text} for every ## heading found.
    Only top-level (##) headings are captured.
    """
    sections: dict[str, str] = {}
    pattern = re.compile(r"^## (.+)$", re.MULTILINE)
    matches = list(pattern.finditer(content))
    for i, match in enumerate(matches):
        title = match.group(1).strip()
        start = match.end()
        end = matches[i + 1].start() if i + 1 < len(matches) else len(content)
        body = content[start:end].strip()
        sections[title] = body
    return sections


def count_lines(path: Path) -> int:
    """Count non-empty lines in a file."""
    try:
        text = path.read_text(errors="replace")
        return len(text.splitlines())
    except OSError:
        return 0


def is_portified_module(init_path: Path) -> bool:
    """Check whether an __init__.py contains portification markers.

    Returns True if the file contains 'Generated by' or 'Portified from'.
    """
    try:
        text = init_path.read_text(errors="replace")
        return "Generated by" in text or "Portified from" in text
    except OSError:
        return False
