"""Utility helpers for the CLI Portify pipeline."""

from __future__ import annotations

import hashlib
import re
from pathlib import Path
from typing import Any

# ---------------------------------------------------------------------------
# Signal Vocabulary (T03.11)
# ---------------------------------------------------------------------------

STEP_START: str = "step_start"
STEP_COMPLETE: str = "step_complete"
STEP_ERROR: str = "step_error"
STEP_TIMEOUT: str = "step_timeout"
GATE_PASS: str = "gate_pass"
GATE_FAIL: str = "gate_fail"

SIGNAL_VOCABULARY: tuple[str, ...] = (
    STEP_START,
    STEP_COMPLETE,
    STEP_ERROR,
    STEP_TIMEOUT,
    GATE_PASS,
    GATE_FAIL,
)


def parse_frontmatter(content: str) -> tuple[dict[str, Any], str]:
    """Parse YAML-style frontmatter from a Markdown string.

    Returns:
        (frontmatter_dict, body_string) — frontmatter dict is empty if
        the content does not start with '---'.
    """
    if not content.startswith("---"):
        return {}, content

    # Find the closing ---
    rest = content[3:]
    end_idx = rest.find("\n---")
    if end_idx == -1:
        return {}, content

    fm_text = rest[:end_idx].strip()
    body = rest[end_idx + 4:].lstrip("\n")

    fm: dict[str, Any] = {}
    for line in fm_text.splitlines():
        if ":" not in line:
            continue
        key, _, val = line.partition(":")
        key = key.strip()
        val = val.strip()
        # Type coercion: int, float, bool, string
        if val.lower() == "true":
            fm[key] = True
        elif val.lower() == "false":
            fm[key] = False
        else:
            try:
                fm[key] = int(val)
            except ValueError:
                try:
                    fm[key] = float(val)
                except ValueError:
                    fm[key] = val

    return fm, body


def hash_section(content: str) -> str:
    """Return a stable SHA-256 hex digest for section content.

    Leading/trailing whitespace is stripped before hashing.
    """
    normalized = content.strip()
    return hashlib.sha256(normalized.encode("utf-8")).hexdigest()


def extract_sections(content: str) -> dict[str, str]:
    """Extract ## headings and their body text from Markdown content.

    Returns a dict of {section_title: body_text} for every ## heading found.
    Only top-level (##) headings are captured.
    """
    sections: dict[str, str] = {}
    pattern = re.compile(r"^## (.+)$", re.MULTILINE)
    matches = list(pattern.finditer(content))
    for i, match in enumerate(matches):
        title = match.group(1).strip()
        start = match.end()
        end = matches[i + 1].start() if i + 1 < len(matches) else len(content)
        body = content[start:end].strip()
        sections[title] = body
    return sections


def verify_additive_only(old_hashes: dict[str, str], updated: str) -> list[str]:
    """Verify that updated content does not remove or modify existing sections.

    Args:
        old_hashes: Dict of {section_title: hash} from before the update.
        updated: New Markdown content to check.

    Returns:
        List of violation strings (empty if no violations).
    """
    new_sections = extract_sections(updated)
    violations: list[str] = []
    for title, old_hash in old_hashes.items():
        if title not in new_sections:
            violations.append(f"Section '{title}' was removed")
        else:
            new_hash = hash_section(new_sections[title])
            if new_hash != old_hash:
                violations.append(f"Section '{title}' was modified")
    return violations


def count_lines(path: Path) -> int:
    """Count non-empty lines in a file."""
    try:
        text = path.read_text(errors="replace")
        return len(text.splitlines())
    except OSError:
        return 0


def is_portified_module(init_path: Path) -> bool:
    """Check whether an __init__.py contains portification markers.

    Returns True if the file contains 'Generated by' or 'Portified from'.
    """
    try:
        text = init_path.read_text(errors="replace")
        return "Generated by" in text or "Portified from" in text
    except OSError:
        return False
