"""
Install the shared Claude Code user setup: rules, output styles, settings
defaults, and Orca's bundled skills.

- Rules go to ~/.claude/rules/<group>/. Claude Code loads every file under
  ~/.claude/rules/ into every session, so each shipped group is also listed
  in settings.json ``claudeMdExcludes`` by exact path; templates read them
  on demand instead.
- Output styles go to ~/.claude/output-styles/.
- Settings defaults only fill keys the user has not set, so a person's own
  choices are never overwritten. Nested maps (env, plugins, marketplaces,
  per-model settings) are filled entry by entry.
- Orca skills are generated by the Orca CLI for its own version, so they are
  requested from Orca when it is installed rather than shipped here.
- Plugins listed in the defaults are installed with the `claude` CLI, since
  enabling a plugin in settings.json does not download it.
"""

import json
import shutil
import subprocess
import time
from pathlib import Path
from typing import List, Tuple

from .install_hooks import _atomic_write_json, _backup_path

_RULE_GROUPS = ("core", "contextual", "prompts")
_ORCA_SKILLS = ("computer-use", "orca-cli", "orchestration")
_ORCA_CLIS = ("orca-ide", "orca")
# `superclaude install` runs under a 60-second limit in Coder workspaces. The
# Orca and plugin steps download over the network, so together they get a
# bounded share of that; anything unfinished is reported, never fatal.
_ORCA_TIMEOUT = 25
_NETWORK_BUDGET = 30
_NESTED_KEYS = ("env", "enabledPlugins", "extraKnownMarketplaces", "modelSettings")


def _package_dir(name: str) -> Path:
    """Locate src/superclaude/<name> for editable and wheel installs."""
    package_root = Path(__file__).resolve().parent.parent
    editable = package_root / name
    if editable.is_dir():
        return editable
    wheel = package_root / "_src" / "superclaude" / name
    return wheel if wheel.is_dir() else editable


def _copy_tree(source: Path, dest: Path, force: bool) -> Tuple[int, int, List[str]]:
    copied = skipped = 0
    failed: List[str] = []
    for src in sorted(source.rglob("*")):
        if not src.is_file() or "__pycache__" in src.parts or src.name == ".DS_Store":
            continue
        target = dest / src.relative_to(source)
        if target.exists() and not force:
            skipped += 1
            continue
        try:
            target.parent.mkdir(parents=True, exist_ok=True)
            shutil.copy2(src, target)
            copied += 1
        except OSError as exc:
            failed.append(f"{target}: {exc}")
    return copied, skipped, failed


def _load_settings(path: Path) -> Tuple[dict | None, str]:
    if not path.exists():
        return {}, ""
    try:
        data = json.loads(path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError) as exc:
        return None, f"❌ {path} is unreadable or malformed; left untouched ({exc})"
    if not isinstance(data, dict):
        return None, f"❌ {path} is not a JSON object; left untouched"
    return data, ""


def _write_settings(path: Path, data: dict) -> str:
    """Back up and atomically replace settings.json; returns the backup path."""
    path.parent.mkdir(parents=True, exist_ok=True)
    backup = ""
    if path.exists():
        backup_file = _backup_path(path)
        shutil.copy2(path, backup_file)
        backup = str(backup_file)
    _atomic_write_json(path, data)
    return backup


def install_rules(home: Path | None = None, force: bool = False) -> Tuple[bool, str]:
    home = Path.home() if home is None else Path(home)
    source = _package_dir("rules")
    if not source.is_dir():
        return False, f"❌ Rules source not found: {source}"
    rules_dir = home / ".claude" / "rules"
    copied, skipped, failed = _copy_tree(source, rules_dir, force)

    settings_path = home / ".claude" / "settings.json"
    settings, error = _load_settings(settings_path)
    if settings is None:
        return False, error
    excludes = settings.get("claudeMdExcludes", [])
    if not isinstance(excludes, list):
        return (
            False,
            f"❌ {settings_path} claudeMdExcludes is not a list; left untouched",
        )
    wanted = [str(rules_dir / group) + "/**" for group in _RULE_GROUPS]
    missing = [pattern for pattern in wanted if pattern not in excludes]
    if missing:
        settings["claudeMdExcludes"] = excludes + missing
        _write_settings(settings_path, settings)

    message = f"✅ Rules: {copied} installed, {skipped} kept, in {rules_dir} (never auto-loaded)"
    if failed:
        message += "\n❌ " + "\n❌ ".join(failed)
    return not failed, message


def install_output_styles(
    home: Path | None = None, force: bool = False
) -> Tuple[bool, str]:
    home = Path.home() if home is None else Path(home)
    source = _package_dir("output-styles")
    if not source.is_dir():
        return False, f"❌ Output styles source not found: {source}"
    dest = home / ".claude" / "output-styles"
    copied, skipped, failed = _copy_tree(source, dest, force)
    message = f"✅ Output styles: {copied} installed, {skipped} kept, in {dest}"
    if failed:
        message += "\n❌ " + "\n❌ ".join(failed)
    return not failed, message


def apply_settings_defaults(home: Path | None = None) -> Tuple[bool, str]:
    home = Path.home() if home is None else Path(home)
    defaults_path = Path(__file__).resolve().parent / "user_settings_defaults.json"
    try:
        defaults = json.loads(defaults_path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError) as exc:
        return False, f"❌ Settings defaults unreadable at {defaults_path}: {exc}"

    settings_path = home / ".claude" / "settings.json"
    settings, error = _load_settings(settings_path)
    if settings is None:
        return False, error

    added: List[str] = []
    for key, value in defaults.items():
        current = settings.get(key)
        if key in _NESTED_KEYS and isinstance(value, dict):
            if current is None:
                current = settings[key] = {}
            if not isinstance(current, dict):
                continue  # A user value of another shape is theirs; keep it.
            for name, entry in value.items():
                if name not in current:
                    current[name] = entry
                    added.append(f"{key}.{name}")
        elif key not in settings:
            settings[key] = value
            added.append(key)

    if not added:
        return True, "✅ Settings defaults: already present"
    backup = _write_settings(settings_path, settings)
    message = f"✅ Settings defaults: added {len(added)} ({', '.join(added)})"
    if backup:
        message += f"\n💾 Backup: {backup}"
    return True, message


def _find_orca() -> str | None:
    """Return an Orca CLI that answers `skills list`, never another program.

    On Linux a bare `orca` outside Orca's own terminals is usually the GNOME
    screen reader, so each candidate must prove it is Orca before use.
    """
    for name in _ORCA_CLIS:
        path = shutil.which(name)
        if not path:
            continue
        try:
            probe = subprocess.run(
                [path, "skills", "list", "--json"],
                capture_output=True,
                text=True,
                timeout=10,
                stdin=subprocess.DEVNULL,
            )
            topics = json.loads(probe.stdout).get("topics", [])
        except (OSError, subprocess.SubprocessError, ValueError, AttributeError):
            continue
        if probe.returncode == 0 and any(t.get("name") == "orca-cli" for t in topics):
            return path
    return None


def _orca_timeout(deadline: float | None) -> float:
    if deadline is None:
        return _ORCA_TIMEOUT
    return max(1.0, min(_ORCA_TIMEOUT, deadline - time.monotonic()))


def install_orca_skills(
    home: Path | None = None, deadline: float | None = None
) -> Tuple[bool, str]:
    """Ask Orca to install its skills for Claude Code; never fails the install."""
    home = Path.home() if home is None else Path(home)
    skills_dir = home / ".claude" / "skills"
    if all((skills_dir / name / "SKILL.md").exists() for name in _ORCA_SKILLS):
        return True, "✅ Orca skills: already installed"
    orca = _find_orca()
    if orca is None:
        return True, "⏭️  Orca skills: Orca CLI not found; skipped"
    command = [orca, "skills", "install", "--agent", "claude-code"]
    for name in _ORCA_SKILLS:
        command += ["--skill", name]
    try:
        result = subprocess.run(
            command,
            capture_output=True,
            text=True,
            timeout=_orca_timeout(deadline),
            stdin=subprocess.DEVNULL,
        )
    except (OSError, subprocess.SubprocessError) as exc:
        return (
            True,
            f"⚠️  Orca skills: not installed ({exc}); rerun `{orca} skills install`",
        )
    installed = [n for n in _ORCA_SKILLS if (skills_dir / n / "SKILL.md").exists()]
    if result.returncode != 0 or len(installed) != len(_ORCA_SKILLS):
        return True, (
            f"⚠️  Orca skills: installed {len(installed)}/{len(_ORCA_SKILLS)}; "
            f"rerun `{orca} skills install`"
        )
    return True, f"✅ Orca skills: {', '.join(installed)}"


def _read_json(path: Path) -> dict:
    try:
        data = json.loads(path.read_text(encoding="utf-8"))
    except (OSError, ValueError):
        return {}
    return data if isinstance(data, dict) else {}


def install_plugins(
    home: Path | None = None, deadline: float | None = None
) -> Tuple[bool, str]:
    """Download the default plugins the user has not disabled; never fatal."""
    home = Path.home() if home is None else Path(home)
    claude = shutil.which("claude")
    if claude is None:
        return True, "⏭️  Plugins: claude CLI not found; skipped"
    deadline = time.monotonic() + _NETWORK_BUDGET if deadline is None else deadline
    defaults = _read_json(
        Path(__file__).resolve().parent / "user_settings_defaults.json"
    )
    settings = _read_json(home / ".claude" / "settings.json")
    enabled = settings.get("enabledPlugins", {})
    enabled = enabled if isinstance(enabled, dict) else {}
    wanted = [p for p in defaults.get("enabledPlugins", {}) if enabled.get(p) is True]
    plugins_dir = home / ".claude" / "plugins"
    known = _read_json(plugins_dir / "known_marketplaces.json")
    installed = _read_json(plugins_dir / "installed_plugins.json").get("plugins", {})

    commands = []
    for plugin in wanted:
        market = plugin.split("@", 1)[1]
        source = (
            defaults.get("extraKnownMarketplaces", {}).get(market, {}).get("source", {})
        )
        if market not in known and source.get("repo"):
            commands.append(["plugin", "marketplace", "add", source["repo"]])
            known[market] = source
    commands += [
        ["plugin", "install", p, "--scope", "user", "-y"]
        for p in wanted
        if p not in installed
    ]
    if not commands:
        return True, "✅ Plugins: already installed"

    failed = []
    for args in commands:
        remaining = deadline - time.monotonic()
        if remaining < 2:
            failed.append(" ".join(args[1:3]) + f" {args[3]} (time limit)")
            continue
        try:
            result = subprocess.run(
                [claude, *args],
                capture_output=True,
                text=True,
                timeout=remaining,
                stdin=subprocess.DEVNULL,
            )
            if result.returncode != 0:
                failed.append(args[3])
        except (OSError, subprocess.SubprocessError):
            failed.append(args[3])
    if failed:
        return True, (
            f"⚠️  Plugins: not installed: {', '.join(failed)}; "
            "rerun `superclaude install` to retry"
        )
    return True, f"✅ Plugins: installed {', '.join(wanted)}"


def install_user_setup(force: bool = False) -> Tuple[bool, str]:
    """Run every user-setup step; returns combined success and messages."""
    deadline = time.monotonic() + _NETWORK_BUDGET
    results = [
        install_rules(force=force),
        install_output_styles(force=force),
        apply_settings_defaults(),
        install_orca_skills(deadline=deadline),
        install_plugins(deadline=deadline),
    ]
    return all(ok for ok, _ in results), "\n".join(msg for _, msg in results)
